### ISSUE TITLE
Please, provide a short example to how to install for Laravel 8

### ISSUE THREAD

**Issue by SirMishaa** [HealthEngineAU/laravel-logging#15]
Hello ! 

With my team, we will go to Logstash for logging. 

Your library seems to be interesting and to be a turn-key solution. 
Can you provide an example on how to implement your library on Laravel 8?

Does it just act as a new [log driver](https://laravel.com/docs/8.x/logging#available-channel-drivers)?

**Comment by jradtilbrook** [comment]
Hi @SirMishaa, this is pretty much turn-key and yes it adds 2 new log driver channels. All you need to do is set your `LOG_CHANNEL` environment variable to one of `stdout` or `logstash`
